# Em caso de sucesso, test de uma rua -- local
POST http://localhost:8000/temperatura HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "cep":"15771034"
}
###
# -----------------------------------------------------------------------------------------------

# Em caso de falha para retornar cep invalido -- local
POST http://localhost:8000/temperatura HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "cep":"15787"
}
###
# -----------------------------------------------------------------------------------------------
# Em caso de cep valido, porém não encontrado da base -- local
POST http://localhost:8000/temperatura HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "cep":"15771411"
}

###
#----------------------
# Teste na web após o run -- local WEB
POST https://labs-goexpert-870996530558.us-central1.run.app/temperatura HTTP/1.1
Content-Type: application/json

{
    "cep":"15771034"
}